services:

  mysql:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "3306:3306"

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - mysql

  frontend:
    build: ./frontend

    ports:
      - "3000:80"

    depends_on:
      - backend
